before:
  hooks:
    - go mod vendor
builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.Version={{.Version}}

    goarch:
      - amd64
      - arm64

    goos:
      - linux
      - darwin
      - windows

checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
